### ISSUE TITLE
Do you feel like this ever had potential

### ISSUE THREAD

**Issue by randyzwitch** [jverzani/DThree.jl#1]
I've been working on Vega.jl a lot lately, and there are a few D3 graph types I'd love to add. Do you feel like this approach had promise, or was this a failed experiment of sorts?

**Comment by jverzani** [comment]
At the time I wanted something that would reliably make simple graphs (Gadfly, PyPlot and Winston were kinda fledgling at that time and installation was spotty). This was some attempt to mirror the HTML-based graphics stuff in the R world that you know a lot about and a chance for me to learn D3. What I had isn't very Julian and since I'm didn't really have a use case after the other packages became more robust, I just dropped this. Now I see there has been some bit rot since it was last touched, but likely nothing major.

**Comment by randyzwitch** [comment]
Thanks. I'm trying to figure out if I want to take on a similar endeavor to extend the Vega.jl package with charts that don't actually exist in the Vega wrapper.

Maybe I'll fix the bit rot here and see how I like it.
